PROG123/Models/ErrorViewModel.cs
using System;

namespace PROG123.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PROG123/Models/LogInCredentialsModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PROG123.Models
{
    public class LogInCredentialsModel
    {
        public string UserName { get; set; }
        public String UserPassword { get; set; }
    }
}

PROG123/Models/PersonModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PROG123.Models
{
    public class PersonModel
    {
        public String FName { get; set; }
        public String LName { get; set; }
        public String Email { get; set; }
        public String Phone { get; set; }
        public String Address { get; set; }
        public String PersonID { get; set; }
        public String UserName { get; set; }
        public String Password { get; set; }

    }
}

PROG123/Models/ProductModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PROG123.Models
{
    public class ProductModel
    {
        public String Name { get; set; }
        public String Description { get; set; }
        public String PID { get; set; }
        public Double Price { get; set; }
        public int InventoryAmount { get; set; }
    }
}

PROG123/Models/PurchaseModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PROG123.Models
{
    public class PurchaseModel
    {
        public PersonModel PersonModel { get; set; }
        public ProductModel ProductModel { get; set; }
    }
}

PROG123/Models/SalesTransactionModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PROG123.Models
{
    public class SalesTransactionModel
    {

        public string ProductID { get;  set; }
        public string PersonID { get;  set; }
        public DateTime SalesDataTime { get;  set; }
        public int PQuantity { get;  set; }
        public string SalesID { get; set; }
    }
}

PROG123/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Security.Permissions;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using PROG123.DAL;
using PROG123.Models;
using PROG123.utils;

namespace PROG123.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IConfiguration _configuration;

        public HomeController(ILogger<HomeController> logger, IConfiguration configuration)
        {
            _configuration = configuration;
            _logger = logger;
        }

        public IActionResult Index()
        {
            // this is for testing purpuse only.
            DatabaseHelper dbh = new DatabaseHelper(_configuration);
            ConnStatusModel status = dbh.GetConnectionStringAndConnectionStatus();
            ViewBag.ConnStr = status.ConnStr;
            ViewBag.DBStatus = status.DBConnectionStatus;
            ViewBag.Exception = status.Exception;
            return View();
        }

        // add your actions here 

        //firstPage create instant of the PersonModel class and return model
        public IActionResult firstPage()
        {
            var model = new PersonModel();
            return View(model);
        }

      
        /* public IActionResult M...(1... 2...)
         {
             return View(2...);
         }*/

        //secondPage takes PersonModel as parameter which is data submitted from first page 
        //then return model
        //second page display Info

        public IActionResult secondPage(PersonModel person)
        {
            //WEEK_03
            //instantiated dp class and object named _configuration

            DALPerson dp = new DALPerson(_configuration);
            //took a pID var and called AddPerson method which takes person object as parameter
            //adds it to the data store.

            string pID = dp.AddPerson(person);
            
            //The AddPerson method returns the unique identifier (PersonID) of the newly added person
            //changed its name to "pID"

            person.PersonID = pID;

            //session added

            HttpContext.Session.SetString("pID", pID.ToString());
            string strPID = HttpContext.Session.GetString("pID");

            return View(person);
        }

        //WEEK04
        public IActionResult EditPerson()
        {

            string pID = HttpContext.Session.GetString("pID");

            DALPerson dp = new DALPerson(_configuration);

            PersonModel person = dp.getPerson(pID); 
            
            var pmd = new PersonModel();
            
            return View(person); }

        //nextweek //Week05
        public IActionResult UpdatePerson(PersonModel person)
        {
            //Get User ID from Session
            string pID = HttpContext.Session.GetString("pID");
            //Assigned UserID in Person Object
            person.PersonID = pID;

            //instantiate DalPerson class
            DALPerson dp = new DALPerson(_configuration);
            //get UpdatePerson method with person object
            dp.UpdatePerson(person);

            //instead of returning just person object, returned secondPage as view and person object as well
            return View("secondPage",person);
        }
        public IActionResult DeletePerson()
        {

            string pID = HttpContext.Session.GetString("pID");

            DALPerson dp = new DALPerson(_configuration);
            PersonModel person = dp.getPerson(pID);

            dp.DeletePerson(pID);
 
            return View(person);
        }
    }
   
      
}

PROG123/Controllers/NyuntController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Security.Cryptography;
using System.Security.Permissions;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using PROG123.DAL;
using PROG123.Models;
using PROG123.utils;
using static System.Net.Mime.MediaTypeNames;

namespace PROG123.Controllers
{
    public class NyuntController : Controller
    {
        

        private readonly ILogger<NyuntController> _logger;
        private readonly IConfiguration _configuration;

        public NyuntController(ILogger<NyuntController> logger, IConfiguration configuration)
        {
            _configuration = configuration;
            _logger = logger;
        }
        public IActionResult Index()
        {
            return View();
        }

        //Authentication Action
        public IActionResult LogIn(LogInCredentialsModel logInCredentialsModel) {

			//instantiate DalPerson class
			DALPerson dp = new DALPerson(_configuration);

            PersonModel person = dp.CheckLogInCredentials(logInCredentialsModel);


            if (person == null)
            {
                ViewBag.LoginMessage= "Log In Failed";

			}
            else {

				HttpContext.Session.SetString("PersonID", person.PersonID);
				HttpContext.Session.SetString("UserName", person.UserName);
                ViewBag.UserFirstName = person.UserName;

			}

			return View("Index");

		}
    }
}

PROG123/Views/Home/DeletePerson.cshtml
@{
    Layout = null;
}


@model PersonModel

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete Person</title>
</head>
<body>
   
    <h1>
        DELETED
    </h1>
    
</body>
</html>

PROG123/Views/Home/EditPerson.cshtml
@{
    Layout = null;
}

@*included PersonModel*@

@model PersonModel

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit Info</title>
</head>
<body>

    @*initiated the EditMyInfo Method from Homecontroller*@
    @*takes information/input*@

    @using (Html.BeginForm("UpdatePerson", "Home", FormMethod.Post))
    {
                <label for="FName">First Name:</label>
                <input type="text" name="FName" id="FName" value="@Model.FName">

                <br>

                <label for="LName">Last Name:</label>
                <input type="text" name="LName" id="LName" value="@Model.LName">

                <br>

                <label for="Email">Email:</label>
                <input type="email" name="Email" id="Email" value="@Model.Email">

                <br>

                <label for="Phone">Phone:</label>
                <input type="text" name="Phone" id="Phone" value="@Model.Phone">

                <br>

                <label for="Address">Address:</label>
                <input type="text" name="Address" id="Address" value="@Model.Address">

                <br>

                <label for="UserName">Username:</label>
                <input type="text" name="UserName" id="UserName" value="@Model.UserName">

                <br>

                <label for="Password">Password:</label>
                <input type="password" name="Password" id="Password" value="@Model.Password">

                <br>

                <input type="submit" value="Submit">
    }
</body>
</html>

PROG123/Views/Home/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <h3>
        Status of the connection string and DB Connection <br /><br />
        Connection String:: @ViewBag.ConnStr
        <br />
        Database Connection:: @ViewBag.DBStatus
    </h3>
    <br />
    <h3 style="color:red;">Exception:: @ViewBag.Exception</h3>
    <br>
</br>
    @*linked first page of the homework*@

    <a href="@Url.Action("firstPage","Home")">Go to firstPage of homework</a>
    
</body>
</html>

PROG123/Views/Home/firstPage.cshtml
@{
    Layout = null;
}

@*included PersonModel*@

@model PersonModel

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>First Page</title>
</head>
<body>

    @*initiated the secondPage Method from Homecontroller*@
    @*takes information/input*@

    @using (Html.BeginForm("secondPage", "Home", FormMethod.Post))
    {
            <label for="FName">First Name:</label>
            <input type="text" name="FName" id="FName" value="@Model.FName">

            <br>

            <label for="LName">Last Name:</label>
            <input type="text" name="LName" id="LName" value="@Model.LName">

            <br>

            <label for="Email">Email:</label>
            <input type="email" name="Email" id="Email" value="@Model.Email">

            <br>

            <label for="Phone">Phone:</label>
            <input type="text" name="Phone" id="Phone" value="@Model.Phone">

            <br>

            <label for="Address">Address:</label>
            <input type="text" name="Address" id="Address" value="@Model.Address">

            <br>

            <label for="UserName">Username:</label>
            <input type="text" name="UserName" id="UserName" value="@Model.UserName">

            <br>

            <label for="Password">Password:</label>
            <input type="password" name="Password" id="Password" value="@Model.Password">

            <br>

            <input type="submit" value="Submit">
    }
</body>
</html>

PROG123/Views/Home/secondPage.cshtml
@{
    Layout = null;
}


@model PersonModel


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Second Page</title>
</head>
<body>

    @* <h1> Hello world</h1> *@

@*Mapped information stored in Person Model and Displayed*@

<h2>Account Information</h2>
<p>First Name: @Model.FName</p>
<p>Last Name: @Model.LName</p>
<p>Email: @Model.Email</p>
<p>Phone: @Model.Phone</p>
<p>Address: @Model.Address</p>
<p>Username: @Model.UserName</p>
<p>Password: @Model.Password</p>

     <a href="@Url.Action("index","Home")">Go to index of homework</a><br></br>
     <a href="@Url.Action("firstPage","Home")">Go to firstPage of homework</a><br></br>
     <a href="@Url.Action("EditPerson","Home")">Go to Edit Person</a>
     <a href="@Url.Action("DeletePerson","Home")"> Delete Person</a>
</body>
</html>

PROG123/Views/Nyunt/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_NyuntLayout.cshtml";
}

@model PROG123.Models.LogInCredentialsModel;

<form id="loginForm" asp-action="LogIn" method="post">
	<div class="inputwrap">
		<label>Name:</label>
		<input asp-for="UserName" class="roundCorners" required size="15" onclick="value='jdane'"/></br>
	</div>
	<div class="inputwrap">
		<label> Password:</label>
		<input asp-for="UserPassword" class="roundCorners" required size="15" onclick="value='abc123'"/></br>
	</div>
	<div class="inputwrap">
		<label><button type="submit"> Log In </button></label>
		<label style="color:red;">@ViewBag.LoginMessage</label>
	</div>
</form>

PROG123/Views/Shared/_GrievousLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/css/GrievousCSS.css" rel="stylesheet" />
</head>
<body>
    <header>
        <img src="~/images/grievous_banner.jpg" />
        <br />
        <p id="headerText">Welcome @ViewBag.UserFirstName</p>
    </header>

    <div id="content">
        <article>
            @RenderBody()
        </article>
    </div>

    <nav>
        <ul>
            <li>Home</li>
            <li>Shopping</li>
            <li>About</li>
            <li><a href="@Url.Action("ListAllProducts","Grievous")">Show Products</a></li>
            <li><a href="@Url.Action("EnterNewProduct","Grievous")">Add Products</a></li>
            <li><a href="@Url.Action("Index","Home")">SignUp</a></li>
        </ul>
    </nav>

    <footer>
        -contact  -partners   -bleh   -bleh
    </footer>
</body>
</html>

PROG123/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PROG123</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PROG123</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - PROG123 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

PROG123/Views/Shared/_NyuntLayout.cshtml
<!DOCTYPE html>

<html lang="en">
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
   <link href="~/css/NyuntCSS.css" rel="stylesheet" />
</head>
<body>

    <header>
       @* <img src="~/images/vader.png"></img> *@
        <br></br>
        <p id="headerText"> Welcome @ViewBag.UserFirstName </p>
    </header>
    

    <div id="content">
        <article>
            @RenderBody()
        </article>

        <nav >
                <ul>
                    <li>Home</li>
                    <li>Shop</li>
                    <li>About</li>
                    <li><a href="@Url.Action("ListAllProducts","Nyunt")">Show Products</a></li>
                    <li><a href="@Url.Action("EnterNewProduct","Nyunt")">Add Products</a></li>
                    <li><a href="@Url.Action("Index","Home")">Sign Up</a></li>
               </ul>
          </nav>
    </div>

 
    <footer>
        copy right Khant Nyunt
    </footer>
</body>
</html>